version: '3'
services:
  airflow:
    image: "puckel/docker-airflow"
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/usr/local/airflow/dags
      - ./files:/usr/local/airflow/files
    environment:
      LOAD_EX: y
